title: QuakeReloaded
description: A library that provides API to interface Reloaded II mods with Quake Enhanced
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one